### PR TITLE
Girl Select scene

### PR DESCRIPTION
**Pull request by abnermtj**
Assets/Scenes/BrothelGirlSelect.unity

Controls
[A] [D] to choose between girls, only ginger and candy can be select
[Enter] to select,  you will see a flash of the ui then no longer are able to move about the scene

The GirlSelectController object in the scene has a script which controls all the behaviour.
Transition out of this scene in Selected() of GirlSelect.cs

TODO Set Ledger variable for the choice made
TODO Transition out of this scene back to the main game

### CODE REVIEW

**Review by kaixin-hc — COMMENTED** [review]
Screenshot 2023-03-17 at 1 14 35 PM

I'm not sure where this info is saved, but there are several typos in names (and it also looks kinda inconsistent between folders)

This looks great and I think it would work well as an MVP!

One comment would be I don't see where you used RandomEyeBlink and TeleportOnCollide --is there a way to search for usages of a script in Unity? So I didn't test those parts, will you be doing more with it?

finally the selection behaviour looks rlly weird with the flickering of colours. Is this because you haven't implemented the clicking out of the scene yet?

**Comment by kaixin-hc** [comment]
oh oh i realise RandomEyeBlink and TeleportOnCollide is just renamings
so its all g abt that

**Comment by abnermtj** [comment]
I haven't implemented changing out of the scene yet left to James when he intergrates it into level one.

**Comment by abnermtj** [comment]
Will be changing the flickering behavior and typos

**Pull request merged**
